<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE student [
        <!ELEMENT student (id,name,age,gpa,isGraduated,gender,subjects)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT gpa (#PCDATA)>
        <!ELEMENT isGraduated (#PCDATA)>
        <!ELEMENT gender (#PCDATA)>
        <!ELEMENT subjects (subject)*>
        <!ELEMENT subject (subjectId|credits|subjectName|grade)*>
        <!ELEMENT subjectId (#PCDATA)>
        <!ELEMENT credits (#PCDATA)>
        <!ELEMENT subjectName (#PCDATA)>
        <!ELEMENT grade (#PCDATA)>
        ]>
<student>
    <id>1</id>
    <name>Denis</name>
    <age>20</age>
    <gpa>3.5</gpa>
    <isGraduated>false</isGraduated>
    <gender>M</gender>
    <subjects>
        <subject>
            <subjectId>1</subjectId>
            <credits>6</credits>
            <subjectName>IS</subjectName>
            <grade>57</grade>
        </subject>
        <subject>
            <subjectId>2</subjectId>
            <credits>6</credits>
            <subjectName>Web Services</subjectName>
            <grade>57</grade>
        </subject>
        <subject>
            <subjectId>3</subjectId>
            <credits>3</credits>
            <subjectName>Multi-threaded Programming</subjectName>
            <grade>57</grade>
        </subject>
    </subjects>
</student>
